// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.1
// source: article.proto

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticleRpcServiceClient is the client API for ArticleRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleRpcServiceClient interface {
	// 软文列表
	ListArticle(ctx context.Context, in *ListArticleParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 软文详情
	ArticleInfo(ctx context.Context, in *ArticleInfoParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 创建软文
	AddArticle(ctx context.Context, in *EditArticleParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 编辑软文
	EditArticle(ctx context.Context, in *EditArticleParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 软文审核
	ReviewArticle(ctx context.Context, in *ReviewArticleParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 删除软文
	DeleteArticle(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 标签列表
	ListLabel(ctx context.Context, in *ListLabelParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 标签详情
	LabelInfo(ctx context.Context, in *LabelInfoParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 修改标签状态
	UpdateLabel(ctx context.Context, in *UpdateLabelParams, opts ...grpc.CallOption) (*ArticleResp, error)
	// 删除标签
	DeleteLabel(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*ArticleResp, error)
}

type articleRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleRpcServiceClient(cc grpc.ClientConnInterface) ArticleRpcServiceClient {
	return &articleRpcServiceClient{cc}
}

func (c *articleRpcServiceClient) ListArticle(ctx context.Context, in *ListArticleParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/ListArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) ArticleInfo(ctx context.Context, in *ArticleInfoParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/ArticleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) AddArticle(ctx context.Context, in *EditArticleParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/AddArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) EditArticle(ctx context.Context, in *EditArticleParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/EditArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) ReviewArticle(ctx context.Context, in *ReviewArticleParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/ReviewArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) DeleteArticle(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/DeleteArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) ListLabel(ctx context.Context, in *ListLabelParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/ListLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) LabelInfo(ctx context.Context, in *LabelInfoParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/LabelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) UpdateLabel(ctx context.Context, in *UpdateLabelParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/UpdateLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleRpcServiceClient) DeleteLabel(ctx context.Context, in *DeleteParams, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, "/article.ArticleRpcService/DeleteLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleRpcServiceServer is the server API for ArticleRpcService service.
// All implementations must embed UnimplementedArticleRpcServiceServer
// for forward compatibility
type ArticleRpcServiceServer interface {
	// 软文列表
	ListArticle(context.Context, *ListArticleParams) (*ArticleResp, error)
	// 软文详情
	ArticleInfo(context.Context, *ArticleInfoParams) (*ArticleResp, error)
	// 创建软文
	AddArticle(context.Context, *EditArticleParams) (*ArticleResp, error)
	// 编辑软文
	EditArticle(context.Context, *EditArticleParams) (*ArticleResp, error)
	// 软文审核
	ReviewArticle(context.Context, *ReviewArticleParams) (*ArticleResp, error)
	// 删除软文
	DeleteArticle(context.Context, *DeleteParams) (*ArticleResp, error)
	// 标签列表
	ListLabel(context.Context, *ListLabelParams) (*ArticleResp, error)
	// 标签详情
	LabelInfo(context.Context, *LabelInfoParams) (*ArticleResp, error)
	// 修改标签状态
	UpdateLabel(context.Context, *UpdateLabelParams) (*ArticleResp, error)
	// 删除标签
	DeleteLabel(context.Context, *DeleteParams) (*ArticleResp, error)
	mustEmbedUnimplementedArticleRpcServiceServer()
}

// UnimplementedArticleRpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticleRpcServiceServer struct {
}

func (UnimplementedArticleRpcServiceServer) ListArticle(context.Context, *ListArticleParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticle not implemented")
}
func (UnimplementedArticleRpcServiceServer) ArticleInfo(context.Context, *ArticleInfoParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleInfo not implemented")
}
func (UnimplementedArticleRpcServiceServer) AddArticle(context.Context, *EditArticleParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArticle not implemented")
}
func (UnimplementedArticleRpcServiceServer) EditArticle(context.Context, *EditArticleParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditArticle not implemented")
}
func (UnimplementedArticleRpcServiceServer) ReviewArticle(context.Context, *ReviewArticleParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewArticle not implemented")
}
func (UnimplementedArticleRpcServiceServer) DeleteArticle(context.Context, *DeleteParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedArticleRpcServiceServer) ListLabel(context.Context, *ListLabelParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLabel not implemented")
}
func (UnimplementedArticleRpcServiceServer) LabelInfo(context.Context, *LabelInfoParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelInfo not implemented")
}
func (UnimplementedArticleRpcServiceServer) UpdateLabel(context.Context, *UpdateLabelParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLabel not implemented")
}
func (UnimplementedArticleRpcServiceServer) DeleteLabel(context.Context, *DeleteParams) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLabel not implemented")
}
func (UnimplementedArticleRpcServiceServer) mustEmbedUnimplementedArticleRpcServiceServer() {}

// UnsafeArticleRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleRpcServiceServer will
// result in compilation errors.
type UnsafeArticleRpcServiceServer interface {
	mustEmbedUnimplementedArticleRpcServiceServer()
}

func RegisterArticleRpcServiceServer(s grpc.ServiceRegistrar, srv ArticleRpcServiceServer) {
	s.RegisterService(&ArticleRpcService_ServiceDesc, srv)
}

func _ArticleRpcService_ListArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticleParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).ListArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/ListArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).ListArticle(ctx, req.(*ListArticleParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_ArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleInfoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).ArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/ArticleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).ArticleInfo(ctx, req.(*ArticleInfoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_AddArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditArticleParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).AddArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/AddArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).AddArticle(ctx, req.(*EditArticleParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_EditArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditArticleParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).EditArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/EditArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).EditArticle(ctx, req.(*EditArticleParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_ReviewArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewArticleParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).ReviewArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/ReviewArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).ReviewArticle(ctx, req.(*ReviewArticleParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/DeleteArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).DeleteArticle(ctx, req.(*DeleteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_ListLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabelParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).ListLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/ListLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).ListLabel(ctx, req.(*ListLabelParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_LabelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelInfoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).LabelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/LabelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).LabelInfo(ctx, req.(*LabelInfoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_UpdateLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLabelParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).UpdateLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/UpdateLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).UpdateLabel(ctx, req.(*UpdateLabelParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleRpcService_DeleteLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRpcServiceServer).DeleteLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleRpcService/DeleteLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRpcServiceServer).DeleteLabel(ctx, req.(*DeleteParams))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleRpcService_ServiceDesc is the grpc.ServiceDesc for ArticleRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleRpcService",
	HandlerType: (*ArticleRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArticle",
			Handler:    _ArticleRpcService_ListArticle_Handler,
		},
		{
			MethodName: "ArticleInfo",
			Handler:    _ArticleRpcService_ArticleInfo_Handler,
		},
		{
			MethodName: "AddArticle",
			Handler:    _ArticleRpcService_AddArticle_Handler,
		},
		{
			MethodName: "EditArticle",
			Handler:    _ArticleRpcService_EditArticle_Handler,
		},
		{
			MethodName: "ReviewArticle",
			Handler:    _ArticleRpcService_ReviewArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _ArticleRpcService_DeleteArticle_Handler,
		},
		{
			MethodName: "ListLabel",
			Handler:    _ArticleRpcService_ListLabel_Handler,
		},
		{
			MethodName: "LabelInfo",
			Handler:    _ArticleRpcService_LabelInfo_Handler,
		},
		{
			MethodName: "UpdateLabel",
			Handler:    _ArticleRpcService_UpdateLabel_Handler,
		},
		{
			MethodName: "DeleteLabel",
			Handler:    _ArticleRpcService_DeleteLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
