// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: ems.proto

package ems

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_ems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_ems_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EmsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipientEmail []string `protobuf:"bytes,1,rep,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Cc             []*Cc    `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Subject        string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SendType       string   `protobuf:"bytes,4,opt,name=send_type,json=sendType,proto3" json:"send_type,omitempty"`
	SendBody       string   `protobuf:"bytes,5,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
	SenderName     string   `protobuf:"bytes,6,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderMail     string   `protobuf:"bytes,7,opt,name=sender_mail,json=senderMail,proto3" json:"sender_mail,omitempty"`
	SenderPwd      string   `protobuf:"bytes,8,opt,name=sender_pwd,json=senderPwd,proto3" json:"sender_pwd,omitempty"`
	Host           string   `protobuf:"bytes,9,opt,name=host,proto3" json:"host,omitempty"`
	Port           string   `protobuf:"bytes,10,opt,name=port,proto3" json:"port,omitempty"`
	Protocol       string   `protobuf:"bytes,11,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Key            string   `protobuf:"bytes,12,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *EmsReq) Reset() {
	*x = EmsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsReq) ProtoMessage() {}

func (x *EmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsReq.ProtoReflect.Descriptor instead.
func (*EmsReq) Descriptor() ([]byte, []int) {
	return file_ems_proto_rawDescGZIP(), []int{1}
}

func (x *EmsReq) GetRecipientEmail() []string {
	if x != nil {
		return x.RecipientEmail
	}
	return nil
}

func (x *EmsReq) GetCc() []*Cc {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmsReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmsReq) GetSendType() string {
	if x != nil {
		return x.SendType
	}
	return ""
}

func (x *EmsReq) GetSendBody() string {
	if x != nil {
		return x.SendBody
	}
	return ""
}

func (x *EmsReq) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *EmsReq) GetSenderMail() string {
	if x != nil {
		return x.SenderMail
	}
	return ""
}

func (x *EmsReq) GetSenderPwd() string {
	if x != nil {
		return x.SenderPwd
	}
	return ""
}

func (x *EmsReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EmsReq) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *EmsReq) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *EmsReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Cc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Cc) Reset() {
	*x = Cc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc) ProtoMessage() {}

func (x *Cc) ProtoReflect() protoreflect.Message {
	mi := &file_ems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc.ProtoReflect.Descriptor instead.
func (*Cc) Descriptor() ([]byte, []int) {
	return file_ems_proto_rawDescGZIP(), []int{2}
}

func (x *Cc) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Cc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RequestID string `protobuf:"bytes,3,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Path      string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Data      *Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EmsResp) Reset() {
	*x = EmsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmsResp) ProtoMessage() {}

func (x *EmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmsResp.ProtoReflect.Descriptor instead.
func (*EmsResp) Descriptor() ([]byte, []int) {
	return file_ems_proto_rawDescGZIP(), []int{3}
}

func (x *EmsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *EmsResp) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *EmsResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EmsResp) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ems_proto protoreflect.FileDescriptor

var file_ems_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x6d, 0x73,
	0x22, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd5, 0x02, 0x0a,
	0x06, 0x45, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x17, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x65,
	0x6d, 0x73, 0x2e, 0x63, 0x63, 0x52, 0x02, 0x63, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x77, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x77, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x02, 0x63, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x07, 0x45, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x65, 0x6d, 0x73, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x62, 0x0a, 0x0d, 0x45, 0x6d, 0x73, 0x52, 0x70,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x45, 0x6d, 0x73, 0x52, 0x70, 0x63, 0x12, 0x0b, 0x2e, 0x65, 0x6d, 0x73, 0x2e, 0x45, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x65, 0x6d, 0x73, 0x2e, 0x45, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x27, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x73, 0x52, 0x70, 0x63,
	0x12, 0x0b, 0x2e, 0x65, 0x6d, 0x73, 0x2e, 0x45, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x65, 0x6d, 0x73, 0x2e, 0x45, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x65, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ems_proto_rawDescOnce sync.Once
	file_ems_proto_rawDescData = file_ems_proto_rawDesc
)

func file_ems_proto_rawDescGZIP() []byte {
	file_ems_proto_rawDescOnce.Do(func() {
		file_ems_proto_rawDescData = protoimpl.X.CompressGZIP(file_ems_proto_rawDescData)
	})
	return file_ems_proto_rawDescData
}

var file_ems_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ems_proto_goTypes = []interface{}{
	(*Data)(nil),    // 0: ems.Data
	(*EmsReq)(nil),  // 1: ems.EmsReq
	(*Cc)(nil),      // 2: ems.cc
	(*EmsResp)(nil), // 3: ems.EmsResp
}
var file_ems_proto_depIdxs = []int32{
	2, // 0: ems.EmsReq.cc:type_name -> ems.cc
	0, // 1: ems.EmsResp.data:type_name -> ems.Data
	1, // 2: ems.EmsRpcService.CheckEmsRpc:input_type -> ems.EmsReq
	1, // 3: ems.EmsRpcService.SendEmsRpc:input_type -> ems.EmsReq
	3, // 4: ems.EmsRpcService.CheckEmsRpc:output_type -> ems.EmsResp
	3, // 5: ems.EmsRpcService.SendEmsRpc:output_type -> ems.EmsResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ems_proto_init() }
func file_ems_proto_init() {
	if File_ems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ems_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ems_proto_goTypes,
		DependencyIndexes: file_ems_proto_depIdxs,
		MessageInfos:      file_ems_proto_msgTypes,
	}.Build()
	File_ems_proto = out.File
	file_ems_proto_rawDesc = nil
	file_ems_proto_goTypes = nil
	file_ems_proto_depIdxs = nil
}
